name: "RedSock/ReDocs"
description: "Creates documentation based on config file"

author: "RedSock"

branding:
  icon: "book"
  color: "red"

inputs:
  token:
    description: "github token"
    required: true
  base:
    description: "url base"
    required: false
  redocs_config:
    description: "url to redocs config"
outputs:
  link:
    value: ${{ steps.deploy.outputs.tag }}
    description: "documentations link"
runs:
  using: "composite"
  steps:
    - name: Validate
      env:
        REDOCS_CONFIG: ${{ inputs.redocs_config}}
      shell: python
      run: |
        import os
        
        if os.environ['REDOCS_CONFIG'] == '':
            raise Exception('ReDocs config is not configured')

    - uses: actions/checkout@v4
      with:
        repository: 'https://github.com/Red-Sock/ReDocs.git'

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
      run: yarn install

    - name: Build
      env:
        BASE: ${{ inputs.base }}
        REDOCS_CONFIG: ${{ inputs.redocs_config }}
      shell: bash
      run: |
        rm -f .env
        echo "VITE_BASE=\"${{inputs.base}}\"\nVITE_REDOCS_CONFIG=${{inputs.redocs_config}}" > .env

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Build project
      shell: bash
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.token }}
        publish_dir: ./dist