name: "RedSock/ReDocs"
description: "Creates documentation based on config file"

author: "RedSock"

branding:
  icon: "book"
  color: "red"

inputs:
  token:
    description: "github token"
    required: true
  base:
    description: "url base"
    required: false
  redocs_config:
    description: "url to redocs config"
    required: false
outputs:
  link:
    value: ${{ steps.deploy.outputs.tag }}
    description: "documentations link"
runs:
  using: "composite"
  steps:
    - name: Validation
      id: validation
      env:
        REDOCS_BASE: ${{ inputs.base }}
        REDOCS_CONFIG: ${{ inputs.redocs_config}}
        SERVER_URL: ${{ github.server_url }}
        REPOSITORY: ${{ github.repository }}
        REPOSITORY_NAME: ${{ github.event.repository.name }}
      shell: python
      run: |
        import os
        
        redocs_config = os.environ['REDOCS_CONFIG']
        if redocs_config == '':
            redocs_config = os.environ['SERVER_URL'] + os.environ['REPOSITORY']
        
        base = os.environ['REDOCS_BASE']
        if base == '':
            base = os.environ['REPOSITORY_NAME']
        
        with open(os.environ['GITHUB_OUTPUT'], "a") as f:
            print("{0}={1}".format('base', base), file=f)
            print("{0}={1}".format('config', redocs_config), file=f)

    - uses: actions/checkout@v4
      with:
        repository: 'https://github.com/Red-Sock/ReDocs.git'

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Build project
      env:
        BASE: ${{ steps.validation.base }}
        CONFIG: ${{ steps.validation.config }}
      shell: bash
      run: |
      yarn install
      VITE_BASE=\"$BASE\"\nVITE_REDOCS_CONFIG=$CONFIG npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.token }}
        publish_dir: ./dist